version: "3.8"
services:
  db:
    container_name: postgres_container_neuro_bloom
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      custom_network:
        ipv4_address: 172.40.0.2
  pgadmin:
    container_name: pgadmin4_container_neuro_bloom
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      custom_network:
        ipv4_address: 172.40.0.3

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16


